import React from "react"
import { Card } from "./card"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Card,
  "https://www.figma.com/design/9qaQlSYuimzQjuH2GXNE8b/Code-connect--Test?node-id=31%3A247",
  {
    props: {
      button: figma.boolean("Button"),
      heading: figma.string("Heading"),
      body: figma.string("Body"),
      assetType: figma.enum("Asset Type", {
        Icon: "icon",
        Image: "image",
      }),
      variant: figma.enum("Variant", {
        Stroke: "stroke",
        Default: "default",
      }),
      direction: figma.enum("Direction", {
        Horizontal: "horizontal",
        Vertical: "vertical",
      }),
    },
    example: () => <Card heading="Card" body="Body text for whatever you’d like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story. " showButton={true} buttonText="Click me" onButtonClick={() => alert('Button clicked')} assetType="icon" variant="stroke" direction="vertical" imageSrc="https://via.placeholder.com/150" imageAlt="Placeholder" />,
  },
)
