import React from "react"
import { ListCard } from "./List Card"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ListCard,
  "https://www.figma.com/design/9qaQlSYuimzQjuH2GXNE8b/Code-connect--Test?node-id=36%3A142",
  {
    props: {
      text: figma.string("Text"),
      dissabled: figma.enum("Dissabled", {
        Default: "default",
        Variant2: "variant2",
      }),
    },
    example: (props) => <ListCard />,
  },
)
